[package]
name = "generator"
version = "0.1.0"
authors = ["Maik Klein <maikklein@googlemail.com>"]
edition = "2018"

[dependencies]
vk-parse = "0.2"
vkxml = "0.3"
nom = "4.0"
heck = "0.3"
proc-macro2 = "0.2"
itertools = "0.7"

[dependencies.quote]
version = "0.4.2"

[dependencies.syn]
version = "0.12.14"
features = ["full", "extra-traits"]

