[package]
name = "generator"
version = "0.1.0"
authors = ["Maik Klein <maikklein@googlemail.com>"]
edition = "2018"

[dependencies]
vk-parse = { version = "0.5.0", features = ["vkxml-convert"] }
vkxml = "0.3"
nom = "6.0"
heck = "0.3"
proc-macro2 = "1.0"
itertools = "0.9"
quote = "1.0"

[dependencies.syn]
version = "1.0"
features = ["full", "extra-traits"]
