[package]
name = "generator"
version = "0.1.0"
authors = ["Maik Klein <maikklein@googlemail.com>"]
edition = "2021"
publish = false

[dependencies]
bindgen = "0.64"
heck = "0.4"
itertools = "0.12"
nom = "7.1"
once_cell = "1.7"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.4"
vk-parse = { version = "0.12", features = ["vkxml-convert"] }
vkxml = "0.3"

[dependencies.syn]
version = "1.0"
features = ["full", "extra-traits"]
