[package]
name = "analysis"
version = "2.0.0"
edition = "2021"

[dependencies]
roxmltree = "0.21"
tracing = "0.1"
indexmap = "2"
derive_more = { version = "2", features = ["deref"] }

[dev-dependencies]
tracing-test = "0.2"
